### ISSUE TITLE
How can set a networkInterfaces[].accessConfigs[].natIP property on the script? (GCE)

### ISSUE THREAD

**Issue by joesatriani10** [trailofbits/algo#1123]
Im trying to make the IP Address static when the VM is created, I read the GCE documentation to [Assigning a static external IP address to a new VM instance](url), and it say that I need to explicitly provide  the **networkInterfaces[].accessConfigs[].natIP property** and the external IP I want to use. 

But I search on **algo script** for 3 days and I can't find a way to do it, I try to do this on roles/cloud-gce/tasks/main.yml:

```
- name: Network configured
      gce_net:
        name: "algo-net-{{ algo_server_name }}"
        fwname: "algo-net-{{ algo_server_name }}-fw"
        allowed: "udp:500,4500,{{ wireguard_port }};tcp:22"
        state: "present"
        mode: auto
        src_range: 0.0.0.0/0
        networkInterfaces:
          - accessConfigs:
            - kind: compute#accessConfig
              name: external-nat
              natIP: "{{ IP_subject_alt_name }}"
              type: ONE_TO_ONE_NAT
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file_path  }}"
        project_id: "{{ project_id }}"
```

But at this time the variable is undefined:
**"The task includes an option with an undefined variable. The error was: 'IP_subject_alt_name'"**

Maybe is not the correct way, is there a way to make the server with a static IP when creating the VM?
