### ISSUE TITLE
Error when installing to DigitalOcean [FAILED! => {"msg": "The task includes an option with an undefined variable..."]

### ISSUE THREAD

**Issue by iamvishnurajan** [trailofbits/algo#14387]
When doing a fresh install to DigitalOcean (NYC3), I get the following error shortly after the droplet is actually created on DigitalOcean. The install itself then does not complete.

`fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ip_address'\n\nThe error appears to be in '/Users/Vishnu/algo-master/roles/cloud-digitalocean/tasks/main.yml': line 42, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}`

Full install log is here:

PLAY [localhost] *************************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [localhost]

TASK [Playbook dir stat] *****************************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] *********************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
[WARNING]: The value '' is not a valid IP address or network, passing this value to ipaddr filter
might result in breaking change in future.

TASK [Ensure the requirements installed] *************************************************************
ok: [localhost]

TASK [Set required ansible version as a fact] ********************************************************
ok: [localhost] => (item=ansible-core==2.12.1)

TASK [Verify Python meets Algo VPN requirements] *****************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Verify Ansible meets Algo VPN requirements] ****************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
[WARNING]: Found variable using reserved name: no_log

PLAY [Ask user for the input] ************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [localhost]
[Cloud prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Hetzner Cloud
    7. Vultr
    8. Scaleway
    9. OpenStack (DreamCompute optimised)
    10. CloudStack (Exoscale optimised)
    11. Linode
    12. Install to existing Ubuntu 18.04 or 20.04 server (for more advanced users)
  
Enter the number of your desired provider
:
1^M
TASK [Cloud prompt] **********************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ******************************************************************
ok: [localhost]
[VPN server name prompt]
Name the vpn server
[algo]
:
AlgoVPN-NYC3-20211219^M
TASK [VPN server name prompt] ************************************************************************
ok: [localhost]
[Cellular On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to cellular networks?
[y/N]
:
y^M
TASK [Cellular On Demand prompt] *********************************************************************
ok: [localhost]
[Wi-Fi On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to Wi-Fi?
[y/N]
:
y^M
TASK [Wi-Fi On Demand prompt] ************************************************************************
ok: [localhost]
[Trusted Wi-Fi networks prompt]
List the names of any trusted Wi-Fi networks where macOS/iOS clients should not use "Connect On Demand"
(e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:
^M
TASK [Trusted Wi-Fi networks prompt] *****************************************************************
ok: [localhost]
[Retain the PKI prompt]
Do you want to retain the keys (PKI)? (required to add users in the future, but less secure)
[y/N]
:
n^M
TASK [Retain the PKI prompt] *************************************************************************
ok: [localhost]
[DNS adblocking prompt]
Do you want to enable DNS ad blocking on this VPN server?
[y/N]
:
y^M
TASK [DNS adblocking prompt] *************************************************************************
ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:
y^M
TASK [SSH tunneling prompt] **************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ******************************************************************
ok: [localhost]

PLAY [Provision the server] **************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: macOS 11.6.2
ZIP file created: Dec 14 15:52:34 2021
Python 3.9.9
Runtime variables:
    algo_provider "digitalocean"
    algo_ondemand_cellular "True"
    algo_ondemand_wifi "True"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "True"
    algo_ssh_tunneling "True"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ************************************************************
changed: [localhost]

TASK [Install the requirements] **********************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ******************************************************************
ok: [localhost]

TASK [Generate the SSH public key] *******************************************************************
ok: [localhost]

TASK [Copy the private SSH key to /tmp] **************************************************************
ok: [localhost]

TASK [Include a provisioning role] *******************************************************************
[cloud-digitalocean : pause]
Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
 (output is hidden):

TASK [cloud-digitalocean : pause] ********************************************************************
ok: [localhost]

TASK [cloud-digitalocean : Set the token as a fact] **************************************************
ok: [localhost]

TASK [cloud-digitalocean : Get regions] **************************************************************
ok: [localhost]

TASK [cloud-digitalocean : Set facts about the regions] **********************************************
ok: [localhost]

TASK [cloud-digitalocean : Set default region] *******************************************************
ok: [localhost]
[cloud-digitalocean : pause]
What region should the server be located in?
    1. ams2     Amsterdam 2
    2. ams3     Amsterdam 3
    3. blr1     Bangalore 1
    4. fra1     Frankfurt 1
    5. lon1     London 1
    6. nyc1     New York 1
    7. nyc2     New York 2
    8. nyc3     New York 3
    9. sfo1     San Francisco 1
    10. sfo2     San Francisco 2
    11. sfo3     San Francisco 3
    12. sgp1     Singapore 1
    13. tor1     Toronto 1
  
Enter the number of your desired region
[8]
:
8^M
TASK [cloud-digitalocean : pause] ********************************************************************
ok: [localhost]

TASK [cloud-digitalocean : Set additional facts] *****************************************************
ok: [localhost]

TASK [cloud-digitalocean : Upload the SSH key] *******************************************************
ok: [localhost]

TASK [cloud-digitalocean : Creating a droplet...] ****************************************************
changed: [localhost]

TASK [cloud-digitalocean : set_fact] *****************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ip_address'\n\nThe error appears to be in '/Users/Vishnu/algo-master/roles/cloud-digitalocean/tasks/main.yml': line 42, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

TASK [include_tasks] *********************************************************************************
included: /Users/Vishnu/algo-master/playbooks/rescue.yml for localhost

TASK [debug] *****************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] *************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *******************************************************************************************
localhost                  : ok=35   changed=2    unreachable=0    failed=1    skipped=2    rescued=1    ignored=0

**Comment by gddrt** [comment]
I received this same error attempting to deploy to SFO3 on DigitalOcean with the latest branch (v1.1-134-g7203f33). The droplet was created in my case too.

**Comment by iamvishnurajan** [comment]
I was able to get the install script to complete by editing the following. I think the output from DigitalOcean's API is now different, and so the IP address isn't where the current script expects it. I am not well versed with Ansible, so if someone can confirm the below is safe/accurate, that would be appreciated.

In `/Users/[insert username]/algo-master/roles/cloud-digitalocean/tasks/main.yml`, I edited:

What is presently there towards the end of the file:
```YAML
- block:
  - name: "Create a Floating IP"
    digital_ocean_floating_ip:
      state: present
      oauth_token: "{{ algo_do_token }}"
      droplet_id: "{{ digital_ocean_droplet.data.droplet.id }}"
    register: digital_ocean_floating_ip

  - name: Set the static ip as a fact
    set_fact:
      cloud_alternative_ingress_ip: "{{ digital_ocean_floating_ip.data.floating_ip.ip }}"
  when: alternative_ingress_ip

- set_fact:
    cloud_instance_ip: "{{ digital_ocean_droplet.data.ip_address }}"
    ansible_ssh_user: algo
    ansible_ssh_port: "{{ ssh_port }}"
    cloudinit: true
```

To:
```YAML
- block:
  - name: "Create a Floating IP"
    digital_ocean_floating_ip:
      state: present
      oauth_token: "{{ algo_do_token }}"
      droplet_id: "{{ digital_ocean_droplet.data.droplet.id }}"
    register: digital_ocean_floating_ip

  - name: Set the static ip as a fact
    set_fact:
      cloud_alternative_ingress_ip: "{{ digital_ocean_floating_ip.data.floating_ip.ip }}"

- set_fact:
    cloud_instance_ip: "{{ digital_ocean_floating_ip.data.floating_ip.ip }}"
    ansible_ssh_user: algo
    ansible_ssh_port: "{{ ssh_port }}"
    cloudinit: true
```

For clarity:

- I removed: `when: alternative_ingress_ip`
- Changed `cloud_instance_ip: "{{ digital_ocean_droplet.data.ip_address }}"` to `cloud_instance_ip: "{{ digital_ocean_floating_ip.data.floating_ip.ip }}"`
