### ISSUE TITLE
Deploy to EC2 fails due to no available instance

### ISSUE THREAD

**Issue by danqing** [trailofbits/algo#14557]
I chose the Seoul (`ap-northeast-2`) region of AWS, and when running the cloudformation script I get the following error:

```
Your requested instance type (t2.micro) is not supported in your requested Availability Zone (ap-northeast-2d). Please retry your request by not specifying an Availability Zone or choosing ap-northeast-2a, ap-northeast-2c.
```

Looks like somewhere the code is picking an availability zone explicitly. I can't find where that's done, but can we update the code such that an AZ is chosen automatically?

**Comment by danqing** [comment]
Interesting. What I found is that the AZ assignment is quite stubborn — running the script repeatedly usually results in the same AZ being assigned (and thus fail)..

Or maybe an option (not ideal) is to give the user the ability to specify an AZ themselves, so if the first execution fails, at least they can enter a different AZ.

**Comment by glennschler** [comment]
You can try to set the AZ in your stack.yaml template to something you think is available. Then run algo to see what happens. If manually editing is successful, then it is worth researching how to find a better AZ before launching the Cloudformation stack, or in the stack template but before creating the Subnet.
```
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-2b"
      CidrBlock: 172.16.254.0/23
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
```
