### ISSUE TITLE
EC2 Instance dissapears after a while when type is spot

### ISSUE THREAD

**Issue by daniplaninc** [trailofbits/algo#14581]
**Describe the bug**

VPN stops working after a while when using spot instance EC2 instance is gone and a new one is not created.

**To Reproduce**

1. Create a VPN with instance type spot
2. Wait (a long time)

**Expected behavior**

I expected that in the case of spot type, the request for a new instance would be automatic after the first one expires. But it seems when the spot instance lifetime runs out, it just shuts down.

**Temporary workaround request**

Before I go through the whole process of deploying a brand new VPN stack (with instance type *on_demand*), does anyone know if it's possible to just re-launch an EC2 instance using the existing cloudformation stack? This would make my life much easier and is also an acceptable workaround for me right now, until a more permanent solution is available.

**More context**

I run a VPN for work purposes, that is used very sparsely and 100% uptime is not necessary. That is why I use a EC2 scheduler to shut down servers during the night and weekends.
In the latest deployment of the VPN, I thought I could save even more by changing to spot instance type. However, after a while I noticed that the associated EC2 instance just disappeared (approximately after 1 month).

I looked through logs of the scheduler, and found the exact moment the instance disappeared, but more importantly, I think I discovered a hint as to why it never came back:
`Error stopping instances i-05ef752f9f67f641a, (An error occurred (UnsupportedOperation) when calling the StopInstances operation: You can't stop the Spot Instance 'i-05ef752f9f67f641a' because it is associated with a one-time Spot Instance request. You can only stop Spot Instances associated with persistent Spot Instance requests.)`

So this led me to search for more info, and I saw that when creating a spot instance, you can choose between *one-time* or *persistent* type: [SpotInstanceType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-instancemarketoptions-spotoptions.html#cfn-ec2-launchtemplate-launchtemplatedata-instancemarketoptions-spotoptions-spotinstancetype).

I believe that adding SpotOptions to the EC2 launch template may be the fix for this. Maybe someone else has experience with using spot instance type on AWS and can share their experience?

`SpotOptions:
   SpotInstanceType: persistant`

So the modified Cloudformation template would be something like:

```
...
EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Condition: InstanceIsSpot    # Only create this template if requested
    Properties:                  # a spot instance_market_type in config.cfg
      LaunchTemplateName: !Ref AWS::StackName
      LaunchTemplateData:
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: persistant

  EC2Instance:
    Type: AWS::EC2::Instance
...
```

**Comment by glennschler** [comment]
This is the traditional behavior of spot instances. They terminate when the bid price increases past the set MaxPrice. This was a very common occurrence until AWS made a [change in 2018](https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/). This change is why I felt comfortable implementing spot instances in algo. Plus my testing showed a spot instance was able to continue for several months without interruption https://github.com/trailofbits/algo/pull/14248 

I have not tried `SpotInstanceType: persistent`. It sounds like a good option to investigate. Have you tried? Are you already setting a MaxPrice? I quickly read that you also need to set `InstanceInterruptionBehavior` to `hibernate` or `stop` instead of the default `terminate`. Hibernate may need additional install on the instance. I suggest you set a low `MaxPrice` to be able to trigger frequent interruptions for your testing. I might investigate and test as well.

e.g.
```
      ...
      LaunchTemplateData:
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: persistent
            InstanceInterruptionBehavior: stop
            MaxPrice: 0.001
      ...      
```

**Comment by daniplaninc** [comment]
Hi, thanks for responding :)

I have actually managed to deploy this, with the following changes to the *stack.yaml* file:

```
      InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: persistent # new value
            InstanceInterruptionBehavior: stop # new value
```

plus another required change in the *EC2Instance* section:

```
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 8
            Encrypted: !Ref EbsEncrypted
      InstanceInitiatedShutdownBehavior: stop # changed from "terminate"
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup

```

This allowed me to deploy successfully and also allows me to use the EC2 scheduler to shut down the instance during the night.

I did not set a max price. I am using this for work so frequent interruptions are not really what I am looking for :)

Any way, I will make sure to report back if I encounter any problems. For now this is working fine.
