### ISSUE TITLE
Able to achieve same using docker

### ISSUE THREAD

**Issue by arpitjindal97** [trailofbits/algo#1917]
I'm able to achieve same thing what this project tends to do in a single docker container.

The person deploying my docker image has to do below things manually:

 -  Get certificate from Let's Encrypt manually
 - Generate wireguard peer config
 - Put credentials in `ipsec.secrets`

Above things need to be managed by deployer and it's one time setup

Rest will be taken care using my repo. I have kept my repo private as of now. But I can give few things:

**Dockerfile**
```
FROM alpine:latest

RUN apk update

RUN apk add iptables ip6tables iproute2 

RUN apk add wireguard-tools wireguard-virt

RUN apk add strongswan

COPY wg0.conf /etc/wireguard/wg0.conf

COPY ipsec.d/fullchain.pem /etc/ipsec.d/certs/
COPY ipsec.d/privkey.pem /etc/ipsec.d/private/
COPY ipsec.conf /etc/ipsec.conf
COPY ipsec.secrets /etc/ipsec.secrets

COPY run.sh /run.sh
RUN chmod +x /run.sh

CMD ["/run.sh"]
```

**docker-compose.yml**
```
version: '2.1'
services:
  vpnserver:
    image: arpitjindal1997/myst-multiarch:vpnserver
    cap_add:
     - NET_ADMIN
     - SYS_MODULE
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
     - net.ipv6.conf.all.forwarding=1
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=info
    ports:
     - 51820:51820/udp
     - 500:500/udp
     - 4500:4500/udp
    networks:
      app_net:
        ipv6_address: 2001:3200:3200::20
networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
```

Deployer has to put files in specific paths and create the docker image. It's really portable and easy to use with docker-compose. 

Also, support IPV6 :)
