### ISSUE TITLE
Deprecate OpenSSL CLI dependency 

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#359]
Starting with Ansible 2.3 there is [basic support for SSL key generation](https://docs.ansible.com/ansible/openssl_privatekey_module.html) which adds the dependency of pyOpenSSL to Ansible. Since this will already be an existing dependency; I propose we extend the ansible openssl module to support the features we need for X509 certificate signing and deprecate the requirement of openssl CLI and use of shell where possible.

**Comment by gunph1ld** [comment]
Supports DSA/RSA only

**Comment by jackivanov** [comment]
Required Ansible 2.5

**Comment by jackivanov** [comment]
Blockers https://github.com/pyca/cryptography/issues/4845 and https://github.com/ansible/ansible/issues/53789

**Comment by dguido** [comment]
Hi @defunctio,

Thank you for reporting this issue. This appears to be related to using outdated versions of Ansible.

Current Algo requires:
- Python 3.10+
- Ansible 9.1.0
- Modern OS versions (Ubuntu 22.04 LTS)

The version you're referencing (Ansible 2.3) is no longer supported. Please update to the latest version of Algo and follow the current installation instructions.

Since this issue relates to unsupported versions, I'm closing it. If you encounter problems with current versions, please open a new issue.

Thank you for using Algo!

**Comment by dguido** [comment]
## Update: This is now feasible with modern Ansible (2024)

The `community.crypto` collection now provides comprehensive modules that can fully replace all OpenSSL CLI usage in Algo. Here's what's available:

### Available Modules

1. **Key Generation**
   - `community.crypto.openssl_privatekey` - Generates EC/RSA private keys
   - Supports EC curves including secp384r1 that Algo uses
   - Can generate keys with passphrases

2. **Certificate Operations**
   - `community.crypto.x509_certificate` - Generates certificates with multiple providers:
     - `selfsigned` - Self-signed certificates (for CA)
     - `ownca` - Sign certificates with your own CA
   - `community.crypto.openssl_csr` - Creates certificate signing requests
   - Full support for SubjectAltName extensions

3. **PKCS#12 Support**
   - `community.crypto.openssl_pkcs12` - Generates PKCS#12 files
   - Can bundle certificates with private keys and CA chains

4. **CRL Management**
   - `community.crypto.x509_crl` - Generates certificate revocation lists
   - Can revoke certificates programmatically

### Example Migration

Current Algo approach (OpenSSL CLI):
```bash
{{ openssl_bin }} req -utf8 -new -newkey ec:ecparams/secp384r1.pem ...
{{ openssl_bin }} ca -utf8 -in reqs/{{ item }}.req ...
{{ openssl_bin }} pkcs12 -in certs/{{ item }}.crt ...
```

Modern Ansible approach:
```yaml
- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ipsec_pki_path }}/private/cakey.pem"
    type: ECC
    curve: secp384r1
    passphrase: "{{ CA_password }}"
    cipher: auto

- name: Generate CA certificate
  community.crypto.x509_certificate:
    path: "{{ ipsec_pki_path }}/cacert.pem"
    privatekey_path: "{{ ipsec_pki_path }}/private/cakey.pem"
    privatekey_passphrase: "{{ CA_password }}"
    provider: selfsigned
    subject_alt_name: "{{ subjectAltName }}"
    not_after: "+3650d"

- name: Generate client certificates
  community.crypto.x509_certificate:
    path: "{{ ipsec_pki_path }}/certs/{{ item }}.crt"
    csr_path: "{{ ipsec_pki_path }}/reqs/{{ item }}.csr"
    provider: ownca
    ownca_path: "{{ ipsec_pki_path }}/cacert.pem"
    ownca_privatekey_path: "{{ ipsec_pki_path }}/private/cakey.pem"
    ownca_privatekey_passphrase: "{{ CA_password }}"
```

### Benefits

1. **Pure Ansible** - No shell commands or OpenSSL CLI dependency
2. **Better error handling** - Ansible modules provide structured errors
3. **Idempotency** - Modules handle "already exists" scenarios properly
4. **Cross-platform** - Works anywhere Python cryptography library works
5. **Easier testing** - Can mock/test without OpenSSL binary
6. **No more `no_log` requirements** - Sensitive data handled internally by modules

### Requirements

- `ansible-galaxy collection install community.crypto`
- Python `cryptography` library (already required by many Ansible modules)

### Implementation Notes

The migration would primarily affect `roles/strongswan/tasks/openssl.yml`. All cryptographic operations Algo currently performs via OpenSSL CLI are fully supported by the community.crypto modules:

- EC key generation with secp384r1 curve ✓
- Self-signed CA certificate creation ✓
- CSR generation and signing ✓
- PKCS#12 bundle creation ✓
- CRL generation and certificate revocation ✓

This would make Algo more portable, maintainable, and eliminate the OpenSSL binary dependency entirely.
