### ISSUE TITLE
Custom installation doesn't work

### ISSUE THREAD

**Issue by Stanpol** [trailofbits/algo#973]
### OS / Environment (where do you run Algo on)

```
Linux scw-2c622e 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Scaleway, VPS
```

### Summary of the problem

I'm trying to install the latest algo via `7. Install to existing Ubuntu 16.04 server (Advanced)`. During the installation I get the following fatal error:

```
 __________________________________________________
< TASK [wireguard : WireGuard enabled and started] >
 --------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [123.456.123.456]: FAILED! => {"changed": false, "msg": "Unable to start
 service wg-quick@wg0: Job for wg-quick@wg0.service failed because the control
 process exited with error code. See \"systemctl status wg-quick@wg0.service\"
 and \"journalctl -xe\" for details.\n"}
 _________________________________________________
< RUNNING HANDLER [wireguard : restart wireguard] >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### Steps to reproduce the behavior

1. Select 7
2. Enter your IP
3. Wait

Any ideas what could have gone wrong?

**Comment by jackivanov** [comment]
You need to provide more debug information on this, If you can't, I suggest you not use the advanced installation and choose a cloud one

**Comment by ealeksandrov** [comment]
@Stanpol you can also check https://github.com/trailofbits/algo/issues/972 for same error and possible solution (but on different and unsupported cloud provider).

**Comment by Stanpol** [comment]
@jackivanov FYI, this way of WireGuard installation resolved the problem:

```
---

- name: Determine the running kernel release
  command: uname -r
  register: kernel_release

- name: Add the WireGuard PPA
  apt_repository:
    repo: 'ppa:wireguard/wireguard'

- name: Install the WireGuard packages
  apt:
    name: "{{ item }}"
  with_items:
    - linux-headers-{{ kernel_release.stdout }}
    - linux-headers-generic
    - wireguard-dkms
    - wireguard-tools
```
